name: docblock_update

on:
  pull_request:
    branches: [ "*" ]

jobs:
  update-docblocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0

      - name: Update docblocks
        run: |
          set -euo pipefail
          
          # Constants
          readonly COMPOSER_JSON="composer.json"
          readonly DOCBLOCK_DOCKER_IMAGE="davidsmith3/docblock-annotator-cli"
          readonly DOCBLOCK_COMMAND="docblock-annotator-cli:update-file"
          
          # Execute docblock annotator via Docker for a specific file
          execute_docblock_annotator() {
              local file_path="$1"
              shift
          
              docker run \
                  --rm \
                  --volume "$(pwd):/app/run" \
                  "${DOCBLOCK_DOCKER_IMAGE}" \
                  "${DOCBLOCK_COMMAND}" \
                  "/app/run/${file_path}" \
                  "$@"
          }
          
          # Validate required dependencies are available
          validate_dependencies() {
              if ! command -v jq &> /dev/null; then
                  echo "Error: jq is required but not installed." >&2
                  return 1
              fi
          
              if [[ ! -f "${COMPOSER_JSON}" ]]; then
                  echo "Error: ${COMPOSER_JSON} not found in current directory." >&2
                  return 1
              fi
          }
          
          # Get all PHP files in src directory
          get_src_php_files() {
              find src -name "*.php" -type f | sort
          }
          
          # Extract package description from composer.json
          get_package_description() {
              local description
              description=$(jq -r '.description // empty' "${COMPOSER_JSON}")
          
              if [[ -z "$description" ]]; then
                  echo "Error: Could not extract package description from ${COMPOSER_JSON}." >&2
                  return 1
              fi
          
              echo "$description"
          }
          
          # Extract package homepage from composer.json
          get_package_homepage() {
              local homepage
              homepage=$(jq -r '.homepage // empty' "${COMPOSER_JSON}")
          
              if [[ -z "$homepage" ]]; then
                  echo "Error: Could not extract package homepage from ${COMPOSER_JSON}." >&2
                  return 1
              fi
          
              echo "$homepage"
          }
          
          # Update docblock with package description for all files
          update_docblock_with_description() {
              local php_files description
          
              php_files=$(get_src_php_files)
              description=$(get_package_description) || return 1
          
              for php_file in $php_files; do
                  echo "Updating description for $php_file"
                  execute_docblock_annotator "$php_file" "$description" "--statements=class" || true
              done
          }
          
          # Update docblock with homepage link for all files
          update_docblock_with_link() {
              local php_files homepage
          
              php_files=$(get_src_php_files)
              homepage=$(get_package_homepage) || return 1
          
              for php_file in $php_files; do
                  echo "Updating homepage link for $php_file"
                  execute_docblock_annotator "$php_file" "@link $homepage" || true
              done
          }
          
          # Main function to update all docblocks
          update_package_docblocks() {
              validate_dependencies || return 1
          
              echo "Updating docblocks with package description..."
              update_docblock_with_description || return 1
          
              echo "Updating docblocks with homepage link..."
              update_docblock_with_link || return 1
          
              echo "Docblock updates completed successfully."
          }
          
          # Execute the main function
          update_package_docblocks

      - name: Commit and push changes (if any)
        run: |
          set -euo pipefail
          
          # Configure git user for commits
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Stage all changes
          git add -A
          
          # Check if there are any changes to commit
          if ! git diff --cached --quiet; then
            echo "Changes detected, committing docblock updates..."
          
            # Commit without skip-ci to allow other workflows to run
            git commit -m "Update docblocks with @link annotations" \
                       --no-verify
          
            # Push changes - using PAT_TOKEN if available to trigger workflows properly
            git push
          
            echo "Docblock updates committed and pushed successfully."
            echo "Other workflows will run on the new commit."
          else
            echo "No changes to commit."
          fi